### ISSUE TITLE
[Bug] Extension might break page layout of some webpage

### ISSUE THREAD

**Issue by snsnsjsn** [yiminzme/Multi-Highlight#44]
hi, this sites

http://www.g-medon.com/Item/31390.aspx

when I highlight some words , it will highlight the word to line

and could not to read normally.

![image](https://user-images.githubusercontent.com/11435527/174469551-132907ea-45c2-483a-9598-5d489a8fff20.png)

**Comment by TroyDanielFZ** [comment]
It actually casued by the css rules:
```css
.detailed_content_tit span{width:676px;display:block;text-align:right;color:#1D6AAE;cursor:pointer;margin-bottom:10px;}
```
in the gmedon.css introduced in the page.

Solution: 
1. Modify the css in Multi Highlight extension, add `	display: inline !important;
` to the rule `.chrome-extension-FindManyStrings` in highlight.css.
2. Alternatively, you can use another extension, like user css, create a custom rule, like `.chrome-extension-FindManyStrings { display: inline !important;}`.
